resources:
 - argocd/namespaces/namespace-openshift-storage.yaml
 - argocd/storage.yaml
patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: "gitops.tier.layer=infra"
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/otp-itz/otp-gitops-infra.git
    - op: add
      path: /spec/source/targetRevision
      value: master
